name: Cron 
on:
  schedule:
    # Execute at 21:55 Brasilia (UTC)
    - cron: '55 00 * * *'
  workflow_dispatch:

jobs:
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0

    - name: Scheduled Run Information 
      run: |
        echo "Today is: $(date)"
        echo "UTC: $(date -u)"
        echo "Timezone: $(date +%Z)"

    - name: Daily report
      run: | 
        echo "DAILY REPORT"
        echo "======================"
        echo "Triggered by: ${{github.event_name}}"
        echo "total commits: $(git rev-list --all --count)"
        echo "Contributors:"
        git shortlog -sne --all
        echo "latest commit: $(git log -1 --pretty=format:'%h - %s (%an, %ar)')"